import json
import ollama
from pathlib import Path
import re

# ==========================================
# 1. Prompt Engineering
# ==========================================
SYSTEM_PROMPT = """
You are an expert Frontend Developer and UI Designer. 
Your task is to convert a JSON representation of a Component into semantic HTML using **Tailwind CSS**.

Rules:
1. Use purely Tailwind CSS classes for styling.
2. Interpret "natural language" styles (e.g., "clean white background") into appropriate Tailwind classes (e.g., "bg-white shadow-sm").
3. For loops like `foreach $products`, generate ONE representative HTML item as a template.
4. Use `{{ variable }}` syntax for dynamic data binding found in the JSON.
5. Output ONLY the HTML code. Do not wrap in markdown code blocks like ```html.
"""

# ==========================================
# 2. AI Interaction
# ==========================================
def ask_ai_to_render(component_data):
    """
    컴포넌트 데이터를 받아서 Ollama에게 HTML 생성을 요청
    """
    comp_name = component_data.get("name", "Component")
    
    # AI에게 보낼 메시지 구성
    user_message = f"""
    Render this component: "{comp_name}"
    
    Data/Specs (JSON):
    {json.dumps(component_data, indent=2)}
    
    Generate the HTML snippet for this component now.
    """
    
    print(f"🤖 Asking Qwen2.5 to render: {comp_name}...")
    
    response = ollama.chat(model='qwen2.5:7b', messages=[
        {'role': 'system', 'content': SYSTEM_PROMPT},
        {'role': 'user', 'content': user_message},
    ])
    
    content = response['message']['content']
    
    # 마크다운 제거 (```html ... ```)
    content = re.sub(r"```html", "", content)
    content = re.sub(r"```", "", content)
    
    return content.strip()

# ==========================================
# 3. HTML Assembly
# ==========================================
def build_full_page(ir_data):
    page_name = ir_data.get("name", "Page")
    body_items = ir_data.get("children", [])
    
    rendered_components = []
    
    # 최상위 요소들을 순회하며 각각 AI에게 렌더링 요청
    for item in body_items:
        # 딕셔너리 형태의 컴포넌트만 처리
        if isinstance(item, dict) and item.get("type") == "component":
            html_snippet = ask_ai_to_render(item)
            rendered_components.append(f"\n{html_snippet}")
            
    # 최종 HTML 조립 (Tailwind CDN 포함)
    full_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{page_name}</title>
    <script src="[https://cdn.tailwindcss.com](https://cdn.tailwindcss.com)"></script>
    <style>
        body {{ font-family: sans-serif; background-color: #f3f4f6; padding: 2rem; }}
    </style>
</head>
<body>
    <div class="max-w-7xl mx-auto space-y-8">
        <header class="mb-8">
            <h1 class="text-3xl font-bold text-gray-800">{page_name} Generated by AI</h1>
            <p class="text-gray-500">Powered by DSL & Qwen2.5:7b</p>
        </header>
        
        {'\n\n'.join(rendered_components)}
        </div>
</body>
</html>
"""
    return full_html

# ==========================================
# 4. Main Execution
# ==========================================
if __name__ == "__main__":
    ir_path = Path("page_ir.json")
    
    if not ir_path.exists():
        print("❌ 'page_ir.json' not found. Run compiler.py first.")
        exit(1)
        
    try:
        ir_data = json.loads(ir_path.read_text(encoding="utf-8"))
        
        final_html = build_full_page(ir_data)
        
        Path("index.html").write_text(final_html, encoding="utf-8")
        print("\n✨ Success! 'index.html' has been generated with AI.")
        
    except Exception as e:
        print(f"❌ Error during AI generation: {e}")
        print("Ensure Ollama is running: 'ollama serve' and you have pulled 'qwen2.5:7b'")